version: '3.8'

services:
  api-service:
    container_name: my-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8025:8023'
    networks:
      - mynetwork
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: BatDongSan
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
